# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z03mg5m_EwRg8J-VIIJPLDYZujG4oFJB
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install gdown

import gdown

file_id = '18I3VYO_Le-_cFY6Rmbg1MLbHrwmwPE6F'
output  = '/content/SEP-28k_CLIP.tar.gz'

gdown.download(f'https://drive.google.com/uc?id={file_id}', output, quiet=False)
print("Download complete!")

import os
from huggingface_hub import login
login('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')
import pandas as pd
from transformers import AutoConfig, AutoModel
import torchaudio
import torch
import numpy as np
from datetime import datetime
from tqdm import tqdm
from torch.utils.data import Dataset, DataLoader

extract_to = '/content/data/'
os.makedirs(extract_to, exist_ok=True)

!tar -xzf /content/SEP-28k_CLIP.tar.gz -C {extract_to}
print("Done unpacking!")

from google.colab import files
uploaded = files.upload()

!ls /content/data/
!ls /content/data/SEP-28k_CLIP/

!ls /content/

csv_path   = '/content/SEP-28k-Extended_clips.csv'
clips_path = '/content/data/SEP-28k_CLIP'

# Check CSV
print("CSV exists:", os.path.exists('/content/SEP-28k-Extended_clips.csv'))

# Check one audio clip
path = '/content/data/SEP-28k_CLIP/HeStutters/10/HeStutters_10_0.wav'
print("Exists:", os.path.exists(path))

# Correct Paths
csv_path   = '/content/SEP-28k-Extended_clips.csv'
clips_path = '/content/data/SEP-28k_CLIP'

# Load CSV
df = pd.read_csv(csv_path)

# Build filepath — Show/EpId/Show_EpId_ClipId.wav
df['filepath'] = df.apply(
    lambda row: os.path.join(
        clips_path,
        str(row['Show']),
        str(row['EpId']),
        f"{row['Show']}_{row['EpId']}_{row['ClipId']}.wav"
    ), axis=1
)

# Check how many files exist
df['exists'] = df['filepath'].apply(os.path.exists)
print(f"Total clips in CSV:     {len(df)}")
print(f"Clips found on disk:    {df['exists'].sum()}")
print(f"Clips NOT found:        {(~df['exists']).sum()}")

# Keep only existing files
df = df[df['exists']]
print("\nSample filepath:")
print(df['filepath'].iloc[0])

stutter_cols = ['Prolongation','Block','SoundRep','WordRep','Interjection']

def create_label(row):
  if any(row[col] >= 2 for col in stutter_cols):
    return 1
  elif row['NoStutteredWords'] >=2:
    return 0
  else:
    return -1
df['label'] = df.apply(create_label, axis=1)
df = df[df['label'] != -1]

print(f"Fluent clips:  {len(df[df['label'] == 0])}")
print(f"Stutter clips: {len(df[df['label'] == 1])}")

train_df = df[df['SEP28k-T']== 'train'].reset_index(drop=True)
valid_df = df[df['SEP28k-T']== 'dev'].reset_index(drop=True)
test_df = df[df['SEP28k-T']== 'test'].reset_index(drop=True)

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

# load voc2vec Encoder
print("\n Loading voc2vec encoder...")
MODEL_NAME = "alkiskoudounas/voc2vec-hubert-ls-pt" # facebook/wav2vec2-base, alkiskoudounas/voc2vec-hubert-ls-pt
encoder_config = AutoConfig.from_pretrained(MODEL_NAME)
encoder = AutoModel.from_pretrained(MODEL_NAME, device_map="cuda")

def convo_audio_data(filename):
  try:
    waveform,sample_rate=torchaudio.load(filename)
    #ensures both input and encoder are on the same device
    waveform = waveform.to(device)
    # Stereo to mono
    if waveform.shape[0] > 1:
      waveform = torch.mean(waveform,dim=0,keepdim=True)
    # Resample
    if sample_rate != 16000:
      waveform = torchaudio.functional.sample(
          waveform,
          sample_rate,
          16000,
      )
    # extract features
    emission = encoder(waveform.to(device)).last_hidden_state
    emission = emission.detach().cpu().numpy()
    return emission
  except Exception as e:
    print(f"Error processing {filename}: {e}")
    return None

# Generate embeddings
def generate_embeddings(dataframe,desc):
  x=[]
  y=[]
  discarded = 0
  for _, row in tqdm(dataframe.iterrows(), desc=desc, total=len(dataframe)):
        embedding = convo_audio_data(row['filepath'])

        if embedding is None:
            discarded += 1
        elif ((np.shape(embedding)[0] != 1) |
              (np.shape(embedding)[1] != 149) |
              (np.shape(embedding)[2] != 768)):
            discarded += 1
        else:
            x.append(embedding)
            y.append(row['label'])

  print(f"Discarded in {desc}: {discarded}")
  return x, y

print("\nGenerating embeddings...")
data_start_time = datetime.now()

x_train, y_train = generate_embeddings(train_df, "Train")
x_valid, y_valid = generate_embeddings(valid_df, "Dev")
x_test,  y_test  = generate_embeddings(test_df,  "Test")

print("Time taken: " + str(datetime.now() - data_start_time))

# Hyper Parameters
batch_size    = 256
num_epochs    = 150
learning_rate = 0.0001

n_samples_train = len(x_train)
n_samples_valid = len(x_valid)
n_samples_test  = len(x_test)

print(f'\nTrain samples: {n_samples_train}')
print(f'Dev samples:   {n_samples_valid}')
print(f'Test samples:  {n_samples_test}')

# Dataset Class
class AudioDataset(Dataset):
    def __init__(self, x, y, n_samples):
        self.x         = x
        self.y         = y
        self.n_samples = n_samples

    def __getitem__(self, index):
        return self.x[index], self.y[index]

    def __len__(self):
        return self.n_samples

# Create Datasets & DataLoaders
train_dataset = AudioDataset(x_train, y_train, n_samples_train)
valid_dataset = AudioDataset(x_valid, y_valid, n_samples_valid)
test_dataset  = AudioDataset(x_test,  y_test,  n_samples_test)

train_loader = DataLoader(dataset=train_dataset, batch_size=batch_size,
                          shuffle=True,  num_workers=0)
valid_loader = DataLoader(dataset=valid_dataset, batch_size=batch_size,
                          shuffle=True,  num_workers=0)
test_loader  = DataLoader(dataset=test_dataset,  batch_size=batch_size,
                          shuffle=False, num_workers=0)

print("\n All data loaders ready!")
print(f"Train batches: {len(train_loader)}")
print(f"Valid batches: {len(valid_loader)}")
print(f"Test batches:  {len(test_loader)}")

# Model definition
import torch.nn as nn

class AttentionPooling(nn.Module):
    def __init__(self, hidden_size):
        super(AttentionPooling, self).__init__()
        # Attention layer
        self.attention = nn.Linear(hidden_size, 1)

    def forward(self, x):
        scores  = self.attention(x)                    # → (batch, time_steps, 1)
        weights = torch.softmax(scores, dim=1)         # → (batch, time_steps, 1)
        pooled  = torch.sum(x * weights, dim=1)        # → (batch, hidden_size)
        return pooled


class StutterNet(nn.Module):
    def __init__(self):
        super(StutterNet, self).__init__()

        # Layer 1 - Linear Projection
        # Reduces voc2vec output from 768 → 384
        self.projection = nn.Linear(768, 384)

        # Layer 2 - 1D CNN
        # Looks for local patterns in the audio
        self.cnn = nn.Sequential(
            nn.Conv1d(in_channels=384, out_channels=128, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.Dropout(0.3),
        )

        # Layer 3 - 2 layers of BiLSTM
        # Looks at audio forward and backwards
        self.bilstm = nn.LSTM(
            input_size=128,
            hidden_size=256,
            num_layers=2,
            batch_first=True,
            dropout=0.3,
            bidirectional=True
        )

        # Layer 4 - Attention Pooling
        # Focuses on most important parts of audio
        self.attention = AttentionPooling(hidden_size=512)

        # Layer 5 - Dense Layers
        self.dense = nn.Sequential(
            nn.Linear(512, 256),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(256, 128),
            nn.ReLU(),
            nn.Dropout(0.3),
        )

        # Layer 6 - 5 Output Heads
        # One head per stutter type!
        self.head_prolongation = nn.Linear(128, 2)
        self.head_block        = nn.Linear(128, 2)
        self.head_soundrep     = nn.Linear(128, 2)
        self.head_wordrep      = nn.Linear(128, 2)
        self.head_interjection = nn.Linear(128, 2)

    def forward(self, x):
        # x shape coming in → (batch, 1, 149, 768)
        # Remove extra dimension
        x = x.squeeze(1)

        # Linear Projection
        x = self.projection(x)
        x = torch.relu(x)

        # 1D CNN
        x = x.permute(0, 2, 1)
        x = self.cnn(x)
        x = x.permute(0, 2, 1)

        # BiLSTM
        x, _ = self.bilstm(x)

        # Attention Pooling
        x = self.attention(x)

        # Dense Layers
        x = self.dense(x)

        # 5 Output Heads
        output_prolongation = self.head_prolongation(x)
        output_block        = self.head_block(x)
        output_soundrep     = self.head_soundrep(x)
        output_wordrep      = self.head_wordrep(x)
        output_interjection = self.head_interjection(x)

        return {
            'prolongation': output_prolongation,
            'block':        output_block,
            'soundrep':     output_soundrep,
            'wordrep':      output_wordrep,
            'interjection': output_interjection
        }


# Initialize Model
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model  = StutterNet().to(device)
print(model)